# Generated by Django 5.0.6 on 2024-07-08 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre de Categoría')),
            ],
            options={
                'verbose_name': 'categoría',
                'verbose_name_plural': 'categorías',
                'db_table': 'categoriaEmpleado',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Tipo de empleado')),
            ],
            options={
                'verbose_name': 'TipoEmpleado',
                'verbose_name_plural': 'TiposEmpleados',
                'db_table': 'tipoEmpleado',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=70, verbose_name='Nombres')),
                ('apellido', models.CharField(max_length=70, verbose_name='Apellidos')),
                ('dni', models.CharField(max_length=8, unique=True, verbose_name='D.N.I.')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('cantidad_hijos', models.PositiveIntegerField(null=True, verbose_name='Cantidad de Hijos')),
                ('sexo', models.CharField(max_length=10, null=True)),
                ('fecha_registro', models.DateField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('fecha_actualizacion', models.DateField(auto_now=True)),
                ('salario', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('estado', models.BooleanField(default=True)),
                ('imagen_perfil', models.ImageField(blank=True, null=True, upload_to='imagenPerfil/')),
                ('curriculum_vitae', models.ImageField(blank=True, null=True, upload_to='curriculumVitae/')),
                ('categoria', models.ManyToManyField(to='usuarios.categoria')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.tipo')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'db_table': 'empleado',
                'ordering': ['id'],
            },
        ),
    ]
